Item controller
queens-psyc-clinic/app pull request #82
Opened 2024-03-11 17:50 UTC by victortarn

2024-03-11 18:18 UTC, cainsusk requested changes
Overall looks good !! there's just a few places that should be changed to keep the code readable as well as some duplicated info in the docs. thanks for following the rest-ful style !!

2024-03-11 18:18 UTC, cainsusk commented on app/resources/item.py
> +          Item:
Is the `Item` definition complete ? It doesn't seem to fully describe the `item_fields` definition

2024-03-11 18:18 UTC, cainsusk commented on app/resources/item.py
> +        definitions:
I believe you only need to define the `Item` once, and then reference it as you do above (`$ref: ...`)

2024-03-11 18:18 UTC, cainsusk commented on app/resources/items.py
> +# item_fields = {
perhaps remove this if its not being used

2024-03-11 18:18 UTC, cainsusk commented on app/resources/items.py
> +        definitions:
same here with the duplicated definition

2024-03-11 18:18 UTC, cainsusk commented on app/resources/item.py
> +        definitions:
and if that specific syntax doesn't work, check out how I referenced the `User` definition in `user.py` and `users.py`

2024-03-11 18:18 UTC, cainsusk commented on app/resources/item.py
> +    return execute_query("SELECT * FROM `Items` WHERE `ID` = %s", [(id,)], False)
perhaps use `execute_sql_query` so simplify

2024-03-14 00:45 UTC, closed without merging

2024-03-18 16:36 UTC, victortarn commented on app/resources/items.py
> +def _generate_unique_id():
There are no unique identifiers for the test table so we would need to generate a unique id somehow. I think this way is reliable.